import {isFreeToUseEntry} from './catalog-policy.js';
import {historyLabels, briefText, hasDetailedBrief} from './idea-details.js';
import {licenseBadge, licensePanel} from './license-ui.js';
import {createSpacesApp} from './spaces.js';
import {createAuthUI, workosLogoutURL} from './auth-ui.js';

const $ = selector => document.querySelector(selector);
const E = value => String(value ?? '').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons = {feed:'◉',ideas:'◇',groups:'◎',projects:'▧',saved:'☆',spaces:'▦'};
let session = {}, catalog = [], community = {groups:[],projects:[],posts:[]}, saved = [], feedMode = 'explore', query = '', topic = 'All', ideaHistory = 'All', routeEpoch = 0, dataEpoch = 0;
const idea = address => catalog.find(i=>i.addr===address || i.id===address);
const ideaPath = item => '/ideas/' + encodeURIComponent(item.addr);
const initials = name => String(name || 'Builder').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const avatar = name => `<span class="avatar" aria-hidden="true">${E(initials(name))}</span>`;
const date = value => value ? new Date(value).toLocaleDateString(undefined,{month:'short',day:'numeric'}) : '';
const count = (n, word) => `${n || 0} ${word}${n===1?'':'s'}`;
const spacesApp = createSpacesApp({api,getSession:()=>session,getCatalog:()=>catalog,go,toast,modal,close:()=>close(),formError,requireAccount});
const authUI = createAuthUI({api,getSession:()=>session,go});

async function api(path, body) {
  const response = await fetch('/api/' + path, {method:body===undefined?'GET':'POST', headers:body===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':session.csrf || ''}, body:body===undefined?undefined:JSON.stringify(body)});
  let data;
  try {data=await response.json();} catch {throw Error('Your connection or site login expired. Reload to reconnect; keep a copy of any draft.');}
  if (!response.ok) {const error=Error(data.error || 'We could not complete that action. Try again.');error.status=response.status;error.data=data;throw error;}
  return data;
}
function toast(message) {$('#notice').textContent=message;$('#notice').classList.add('visible');setTimeout(()=>$('#notice').classList.remove('visible'),4500);}
function modal(title, html) {
  const dialog=$('#modal');dialog.setAttribute('aria-label',title);
  $('#modal-body').innerHTML=`<div class="dialog-head"><span>${E(title)}</span><button data-action="close" aria-label="Close dialog">✕</button></div><div class="dialog-content">${html}<p class="error" id="form-error" role="alert" hidden></p></div>`;
  if(!dialog.open)dialog.showModal();
}
const close = () => $('#modal').close();
function formError(error) {const el=$('#form-error');if(el){el.hidden=false;el.textContent=error.message;}else toast(error.message);}
function auth(mode='login') {return authUI.start(mode);}
function requireAccount(action) {const run=()=>Promise.resolve().then(action).catch(error=>$('#modal').open?formError(error):toast(error.message));if(!session.user){return auth('register',run);}return run();}
async function refresh() {const epoch=++dataEpoch;const active=await api('session');if(epoch!==dataEpoch)return;if(active.user?.id!==session.user?.id){community={groups:[],projects:[],posts:[]};saved=[];}session=active;const [next,bookmarks]=await Promise.all([api('community'),session.user?api('community/bookmarks'):Promise.resolve([])]);if(epoch!==dataEpoch)return;community=next;saved=bookmarks;shell();await renderRoute();}
function applyTheme(){let theme='paper';try{theme=localStorage.getItem('lr-theme-mac')?JSON.parse(localStorage.getItem('lr-theme-mac')):'paper';}catch{}document.body.dataset.theme=theme==='phosphor'?'phosphor':'paper';const button=$('#theme');if(button){button.setAttribute('aria-label',`Switch to ${document.body.dataset.theme==='paper'?'dark':'light'} mode`);button.title=button.getAttribute('aria-label');}}
function shell() {
  const pendingAccount = session.authProvider==='workos' && session.onboarding && !session.user;
  const sidebarNote = session.features?.spaces
    ? '<span class="eyebrow">YOUR SPACE, YOUR WIDGETS</span><p>Collect what interests you. Discover related videos and GitHub projects with AI.</p><a href="/spaces">Explore your spaces →</a>'
    : '<span class="eyebrow">BUILD SOMETHING TOGETHER</span><p>Explore ideas and projects with other builders.</p><a href="/about">How it works →</a>';
  $('#community-root').innerHTML=`<header class="topbar"><a class="brand" href="/">[ LOAD AND RUN ]</a><a class="top-search" href="/ideas"><span>⌕</span> Find your next idea <kbd>/</kbd></a><div class="account-actions">${session.user?`<button class="account-button" data-action="account">${avatar(session.user.name)}<span>${E(session.user.name)}</span></button>`:pendingAccount?'<button class="quiet" data-action="logout">Sign out</button><button class="primary" data-action="setup-account">Finish setup</button>':'<button class="quiet" data-action="login">Sign in</button><button class="primary" data-action="register">Create account</button>'}<button id="theme" data-action="theme" aria-label="Switch theme"><span class="theme-disc" aria-hidden="true"></span></button></div></header><div class="app-layout"><aside class="sidebar"><nav aria-label="Main navigation">${[...(session.features?.spaces?[['/spaces','spaces','Spaces']]:[]),['/ideas','ideas','Ideas'],['/saved','saved','Saved ideas'],['/feed','feed','Feed'],['/groups','groups','Groups'],['/projects','projects','Projects']].map(([url,key,label])=>`<a href="${url}" data-nav="${key}"><span aria-hidden="true">${icons[key]}</span>${label}</a>`).join('')}</nav><div class="sidebar-note">${sidebarNote}</div></aside><main id="main" tabindex="-1"><div id="page"><p class="loading">Opening Load and Run…</p></div></main></div>`;applyTheme();
}
function routeName() {const p=location.pathname;return p.startsWith('/account')?'account':p.startsWith('/spaces')?'spaces':p.startsWith('/ideas')?'ideas':p.startsWith('/groups')?'groups':p.startsWith('/projects')?'projects':p.startsWith('/saved')?'saved':'feed';}
async function go(path) {history.pushState({},'',path);await refresh();window.scrollTo(0,0);$('#main')?.focus({preventScroll:true});}
async function renderRoute() {
  spacesApp.dispose();
  const epoch=++routeEpoch;let path=location.pathname;
  if(session.authProvider==='workos' && session.onboarding && !session.user && path!=='/account/setup'){path='/account/setup';history.replaceState({},'',path);}
  if(path==='/' || ['/practice','/practice/','/practice.html'].includes(path)){
    path=session.features?.spaces?'/spaces':'/feed';
    history.replaceState({},'',path);
  }
  document.body.dataset.page=routeName();
  document.querySelectorAll('[data-nav]').forEach(link=>link.dataset.nav===routeName()?link.setAttribute('aria-current','page'):link.removeAttribute('aria-current'));
  const page=$('#page');page.classList.remove('spaces-page');
  try {
    if(path==='/account/setup')await authUI.renderSetup(page);
    else if(path==='/spaces'||path.startsWith('/spaces/'))await spacesApp.render(path);
    else if(path==='/feed')renderFeed();
    else if(path==='/ideas')renderIdeas();
    else if(path==='/saved'){if(!session.user){page.innerHTML=empty('Keep your next steps close','Create an account to save ideas you want to return to.','Join the community','register');}else renderIdeas(true);}
    else if(path.startsWith('/ideas/'))renderIdea(decodeURIComponent(path.slice(7)));
    else if(path==='/groups')renderGroups();
    else if(path.startsWith('/groups/')){const data=await api('community/groups/'+encodeURIComponent(path.slice(8)));if(epoch===routeEpoch)renderGroup(data);}
    else if(path==='/projects')renderProjects();
    else if(path.startsWith('/projects/')){const data=await api('community/projects/'+encodeURIComponent(path.slice(10)));if(epoch===routeEpoch)renderProject(data);}
    else if(path.startsWith('/posts/')){const data=await api('community/posts/'+encodeURIComponent(path.slice(7)));if(epoch===routeEpoch)renderPost(data);}
    else if(path==='/about')renderAbout();
    else if(idea(path.slice(1)))renderIdea(path.slice(1));
    else page.innerHTML=empty('That page is not here','Explore the ideas that are available in the repository.','Explore ideas','ideas');
    if(epoch===routeEpoch)authUI.renderError(page);
  }catch(error){if(epoch===routeEpoch)page.innerHTML=`<div class="empty-state"><h1>We couldn’t open this page</h1><p>${E(error.message)}</p><a href="/feed">Back to the feed →</a></div>`;}
}
function empty(title,copy,button,action){return `<div class="empty-state"><div class="empty-symbol" aria-hidden="true">◇</div><h2>${E(title)}</h2><p>${E(copy)}</p>${button?`<button class="primary" data-action="${action}">${E(button)}</button>`:''}</div>`;}
function intro(eyebrow,title,copy,action='') {return `<div class="page-heading"><div><span class="eyebrow">${E(eyebrow)}</span><h1>${E(title)}</h1><p>${E(copy)}</p></div>${action}</div>`;}
function projectCard(project) {
  const source=idea(project.ideaAddress);return `<article class="project-card"><div class="card-top"><span class="project-symbol" aria-hidden="true">▧</span><span class="stage stage-${E(project.stage||'forming')}">${E(project.stage||'forming')}</span></div><h3><a href="/projects/${E(project.id)}">${E(project.title)}</a></h3><p>${E(project.goal)}</p>${source?`<a class="idea-reference" href="${ideaPath(source)}">◇ ${E(source.name)}</a>`:'<span class="idea-reference own-idea">◆ Original idea</span>'}<div class="card-footer"><span>${count(project.memberCount,'builder')}</span>${project.repository?'<span>GitHub linked ↗</span>':'<span>Looking for a first step</span>'}</div></article>`;
}
function groupCard(group){return `<article class="group-card"><div class="group-symbol" aria-hidden="true">${E(initials(group.name))}</div><div class="group-card-body"><span class="eyebrow">${E(group.topic||'Builders')}</span><h3><a href="/groups/${E(group.id)}">${E(group.name)}</a></h3><p>${E(group.description)}</p><span class="hint">${count(group.memberCount,'member')} · ${group.joined?'You’re a member':'Open to new members'}</span></div><a class="quiet-link" href="/groups/${E(group.id)}">Explore →</a></article>`;}
function ideaCard(item){const isSaved=saved.some(s=>s.ideaAddress===item.addr);return `<article class="idea-card"><div class="card-top"><span class="topic-label">${E(item.domain)}</span><button class="save-button ${isSaved?'saved':''}" data-action="save" data-id="${E(item.addr)}" aria-label="${isSaved?'Unsave':'Save'} ${E(item.name)}" aria-pressed="${isSaved}">${isSaved?'★':'☆'}</button></div><h3><a href="${ideaPath(item)}">${E(item.name)}</a></h3><p>${E(item.line)}</p>${item.details?`<p class="idea-origin"><span>Inspired by</span> ${E(item.details.origin.title)} · ${E(item.details.origin.year)}</p>`:''}<div class="idea-tags">${(item.tags||[]).slice(0,3).map(tag=>`<span>${E(tag)}</span>`).join('')}</div><div class="card-footer"><span>${E(historyLabels[item.details?.history?.status]||'Build opportunity')}</span>${session.features?.spaces?`<button class="text-button" data-action="idea-to-space" data-id="${E(item.addr)}">＋ Space</button>`:''}<button class="license-chip" data-license="${E(item.addr)}" aria-label="Read ${E(item.reuse.name)} license">${E(item.reuse.licenseId||item.reuse.license)} ↗</button></div></article>`;}
function postCard(post,full=false){const source=idea(post.ideaAddress),group=community.groups.find(g=>g.id===post.groupId),project=community.projects.find(p=>p.id===post.projectId);return `<article class="post-card"><div class="post-top">${avatar(post.author?.name)}<div><strong>${E(post.author?.name||'Builder')}</strong><p>${group?`<a href="/groups/${E(group.id)}">${E(group.name)}</a> · `:''}${project?`<a href="/projects/${E(project.id)}">${E(project.title)}</a> · `:''}${date(post.created)}${post.visibility==='members'?' · Members only':''}</p></div>${post.kind==='help'?'<span class="help-label">Help wanted</span>':''}</div><p class="post-body">${E(post.content)}</p>${source?`<a class="post-idea" href="${ideaPath(source)}"><span>◇</span><div><small>BUILDING ON AN IDEA</small><strong>${E(source.name)}</strong></div><span>↗</span></a>`:''}<div class="post-actions"><button data-action="react" data-id="${E(post.id)}" aria-pressed="${!!post.reacted}">${post.reacted?'♥':'♡'} ${post.reactionCount||0}</button><a href="/posts/${E(post.id)}">↳ ${count(post.commentCount,'comment')}</a>${post.canManage?`<button class="muted-action" data-action="remove-post" data-id="${E(post.id)}">Remove</button>`:`<button class="muted-action" data-action="report" data-id="${E(post.id)}">Report</button>`}</div></article>`;}
function composer(scope={}) {return `<button class="composer" data-action="compose" ${scope.groupId?`data-group="${E(scope.groupId)}"`:''} ${scope.projectId?`data-project="${E(scope.projectId)}"`:''}>${avatar(session.user?.name)}<span>${session.user?'Share progress, an idea, or a question…':'What would you like to build?'}</span><strong>＋</strong></button>`;}
function renderFeed(){document.title='Builders feed · Load and Run';const posts=feedMode==='joined'?community.posts.filter(p=>community.groups.some(g=>g.id===p.groupId&&g.joined)||community.projects.some(x=>x.id===p.projectId&&x.joined)||p.owner===session.user?.id):community.posts;$('#page').innerHTML=`<div class="feed-layout"><div><section class="welcome-card"><span class="eyebrow">IDEAS ARE JUST THE BEGINNING</span><h1>Find your people.<br>Build what comes next.</h1><p>Explore ambitious ideas, start a group, and turn a shared question into a working project.</p><div class="welcome-actions"><a class="button primary" href="/ideas">Explore ${catalog.length} ideas <span>→</span></a><a href="/groups">Find a group</a></div></section><div class="section-heading"><h2>From the community</h2><div class="feed-tabs"><button data-action="feed-mode" data-mode="explore" aria-pressed="${feedMode==='explore'}">Explore</button><button data-action="feed-mode" data-mode="joined" aria-pressed="${feedMode==='joined'}">Your groups</button></div></div>${composer()}<div class="posts">${posts.length?posts.map(p=>postCard(p)).join(''):empty(feedMode==='joined'?'Your next chapter starts with a group':'The first update could be yours',feedMode==='joined'?'Join a group or project to follow the work here.':'Share a question, an experiment, or something you’ve started building.',feedMode==='joined'?'Explore groups':'Share an update',feedMode==='joined'?'groups':'compose')}</div></div><aside class="feed-aside"><div class="aside-card"><div class="section-heading"><h3>Ideas to build on</h3><a href="/ideas">All →</a></div>${catalog.slice(0,4).map(item=>`<a class="aside-idea" href="${ideaPath(item)}"><span>◇</span><div><strong>${E(item.name)}</strong><small>${E(item.domain)}</small></div></a>`).join('')}</div><div class="aside-card"><span class="eyebrow">BETTER WITH OTHER BUILDERS</span><h3>Start small. Start together.</h3><p>Create a group around a question you care about. Bring the project and code when you’re ready.</p><button class="quiet wide" data-action="new-group">Start a group</button></div><p class="community-stats">${count(community.groups.length,'group')} · ${count(community.projects.length,'project')}</p></aside></div>`;}
function renderIdeas(onlySaved=false){document.title=(onlySaved?'Saved ideas':'Idea repository')+' · Load and Run';const selected=catalog.filter(item=>(!onlySaved||saved.some(s=>s.ideaAddress===item.addr))&&(topic==='All'||item.domain===topic)&&(ideaHistory==='All'||item.details?.history?.status===ideaHistory)&&[item.name,item.line,item.proposed,briefText(item),...(item.tags||[])].join(' ').toLowerCase().includes(query.toLowerCase()));$('#page').innerHTML=intro('THE IDEA REPOSITORY',onlySaved?'Your next possibilities':'Ideas worth building together','Explore the original ambition, what remains unfinished, and a practical way to build together.',`<button class="quiet" data-action="propose">＋ Propose an idea</button>`)+`<div class="idea-filter"><input id="idea-search" type="search" aria-label="Search ideas" placeholder="Find an idea, topic, or technology" value="${E(query)}"><select id="idea-topic" aria-label="Filter ideas by topic">${['All',...new Set(catalog.map(i=>i.domain))].map(t=>`<option ${topic===t?'selected':''}>${E(t)}</option>`).join('')}</select><select id="idea-history" aria-label="Filter by implementation history"><option value="All">All histories</option>${Object.entries(historyLabels).map(([key,label])=>`<option value="${key}" ${ideaHistory===key?'selected':''}>${E(label)}</option>`).join('')}</select><span>${count(selected.length,'idea')}</span></div><div class="idea-grid">${selected.map(ideaCard).join('')}</div>${selected.length?'':empty('No ideas in this view',onlySaved?'Save ideas from the repository to collect them here.':'Try another search or topic.','Explore all ideas','reset-ideas')}`;$('#idea-search').oninput=event=>{query=event.target.value;const position=event.target.selectionStart;renderIdeas(onlySaved);$('#idea-search').focus();$('#idea-search').setSelectionRange(position,position);};$('#idea-topic').onchange=event=>{topic=event.target.value;renderIdeas(onlySaved);};$('#idea-history').onchange=event=>{ideaHistory=event.target.value;renderIdeas(onlySaved);};}
function renderIdea(address) {
  const item=idea(address);
  if(!item){$('#page').innerHTML=empty('This idea is not in the current repository','Explore the published ideas and their sources.','Explore ideas','ideas');return;}
  document.title=item.name+' · Load and Run';
  const d=item.details, related=community.projects.filter(p=>p.ideaAddress===item.addr);
  const paragraphs=text=>(Array.isArray(text)?text:[text]).filter(Boolean).map(p=>`<p class="prose">${E(p)}</p>`).join('');
  const cite=ids=>`<span class="brief-citations">${(ids||[]).map(id=>{const i=d.references.findIndex(ref=>ref.id===id);return i<0?'':`<a href="#source-${E(id)}" data-idea-section="source-${E(id)}" aria-label="Source ${i+1}: ${E(d.references[i].title)}">[${i+1}]</a>`;}).join(' ')}</span>`;
  const bullets=items=>`<ul class="brief-list">${items.map(text=>`<li>${E(text)}</li>`).join('')}</ul>`;
  const article=d?`
    <div class="brief-origin-line">${E(d.origin.people.join(' · '))} · ${E(d.origin.year)} ${cite(d.origin.sourceIds)}</div><div class="brief-mobile-actions"><button class="primary" data-action="new-project" data-idea="${E(item.addr)}">Start a project →</button><button class="quiet" data-action="save" data-id="${E(item.addr)}">${saved.some(s=>s.ideaAddress===item.addr)?'★ Saved':'☆ Save idea'}</button></div>
    <nav class="brief-toc" aria-label="On this idea page">${[['origin','The original idea'],['gap','What remains'],['today','Why today'],['plan','First project'],['challenges','Challenges'],['sources','Sources'],['reuse','License']].map(([id,label])=>`<a href="#${id}" data-idea-section="${id}">${label}</a>`).join('')}</nav>
    <section id="origin" class="brief-section"><span class="eyebrow">01 · ORIGINS</span><h2>${E(d.origin.title)}</h2>${paragraphs(d.origin.summary)}${cite(d.origin.sourceIds)}</section>
    <section id="gap" class="brief-section"><span class="eyebrow">02 · THE UNFINISHED PART</span><h2>What was built—and what remains</h2><p class="history-label">${E(historyLabels[d.history.status])}</p>${paragraphs(d.history.summary)}<div class="brief-comparison"><div><h3>What already exists</h3>${paragraphs(d.history.whatWasBuilt)}</div><div><h3>The opportunity to explore</h3>${paragraphs(d.history.whatRemains)}</div></div>${cite(d.history.sourceIds)}</section>
    <section id="today" class="brief-section"><span class="eyebrow">03 · WHY REVISIT IT?</span><h2>Who could benefit today</h2>${paragraphs(d.whyNow.summary)}${bullets(d.whyNow.beneficiaries)}${cite(d.whyNow.sourceIds)}</section>
    <section id="plan" class="brief-section"><span class="eyebrow">04 · A FIRST PROJECT</span><h2>Start with something testable</h2><div class="brief-milestone"><span class="eyebrow">FIRST MILESTONE</span><p>${E(d.buildPlan.firstMilestone)}</p></div><ol class="brief-steps">${d.buildPlan.steps.map(step=>`<li><h3>${E(step.title)}</h3><p>${E(step.description)}</p><p class="deliverable"><strong>Deliverable:</strong> ${E(step.deliverable)}</p></li>`).join('')}</ol><h3>What would count as progress?</h3>${bullets(d.buildPlan.successCriteria)}<details class="brief-boundaries"><summary>Keep the first version focused</summary>${bullets(d.buildPlan.nonGoals)}</details><h3 class="roles-heading">Bring these skills together</h3><div class="brief-roles">${d.buildPlan.roles.map(role=>`<div><strong>${E(role.name)}</strong><p>${E(role.contribution)}</p></div>`).join('')}</div></section>
    <section id="challenges" class="brief-section"><span class="eyebrow">05 · OPEN CHALLENGES</span><h2>The hard parts to work through</h2>${d.challenges.map(challenge=>`<div class="brief-challenge"><h3>${E(challenge.title)}</h3><p class="prose">${E(challenge.description)}</p></div>`).join('')}</section>
    <section class="brief-section"><h2>Related work to learn from</h2><div class="related-research">${d.relatedWork.map(work=>`<article><h3><a href="${E(work.url)}" target="_blank" rel="noopener noreferrer">${E(work.title)} ↗</a></h3><p>${E(work.relationship)}</p></article>`).join('')}</div></section>
    <section id="sources" class="brief-section"><span class="eyebrow">06 · SOURCE MATERIAL</span><h2>Read the evidence</h2><ol class="brief-references">${d.references.map(ref=>`<li id="source-${E(ref.id)}"><a href="${E(ref.url)}" target="_blank" rel="noopener noreferrer">${E(ref.title)} ↗</a><p>${E(ref.supports)}</p><small>${E(ref.kind?.replaceAll('-',' ')||'Source material')}</small></li>`).join('')}</ol></section>
  `:`<section><h2>A direction to explore</h2>${paragraphs(item.opportunity||item.proposed)}</section><section><h2>What already exists</h2>${paragraphs(item.existingWork)}</section>`;
  $('#page').innerHTML=`<a class="back-link" href="/ideas">← Idea repository</a><div class="idea-detail-layout"><article class="idea-detail"><span class="eyebrow">${E(item.domain)} · ${E(historyLabels[d?.history?.status]||'Build opportunity')}</span><h1>${E(item.name)}</h1><p class="detail-lead">${E(item.line)}</p><div class="idea-tags">${(item.tags||[]).map(t=>`<span>${E(t)}</span>`).join('')}</div>${article}<section id="reuse" class="brief-section"><h2>Build with licensed source</h2>${licensePanel(item)}</section></article><aside class="brief-sidebar"><div class="start-project-card"><span class="eyebrow">BUILD THIS TOGETHER</span><h3>Turn the idea into a first experiment</h3><p>${E(d?.buildPlan.firstMilestone||'Define a first experiment, gather a group, and keep the code on GitHub.')}</p><button class="primary wide" data-action="new-project" data-idea="${E(item.addr)}">Start a project →</button><button class="quiet wide" data-action="save" data-id="${E(item.addr)}">${saved.some(s=>s.ideaAddress===item.addr)?'★ Saved':'☆ Save for later'}</button>${session.features?.spaces?`<button class="quiet wide" data-action="idea-to-space" data-id="${E(item.addr)}">＋ Add to a space</button>`:''}${d?`<p class="hint">${count(d.buildPlan.steps.length,'milestone')} · ${count(d.references.length,'source')}</p>`:''}</div><div class="aside-card"><h3>Projects exploring this</h3>${related.length?related.map(p=>`<a class="aside-idea" href="/projects/${E(p.id)}"><span>▧</span><div><strong>${E(p.title)}</strong><small>${E(p.stage||'forming')}</small></div></a>`).join(''):'<p>No project yet. Bring a question and start the first one.</p>'}</div></aside></div>`;
  if(location.hash){try{document.getElementById(decodeURIComponent(location.hash.slice(1)))?.scrollIntoView({block:'start'});}catch{}}
}
function renderGroups(){document.title='Groups · Load and Run';$('#page').innerHTML=intro('FIND YOUR PEOPLE','A shared question. A group of builders.','Start a group around an idea, a field, or a problem you want to work on.',`<button class="primary" data-action="new-group">＋ Start a group</button>`)+`<div class="group-list">${community.groups.length?community.groups.map(groupCard).join(''):empty('Make room for your people','Create the first group and give other builders a reason to join.','Start a group','new-group')}</div>`;}
function renderGroup({group,projects,posts,members}){document.title=group.name+' · Load and Run';$('#page').innerHTML=`<a class="back-link" href="/groups">← All groups</a><section class="group-hero"><div class="group-symbol large">${E(initials(group.name))}</div><div><span class="eyebrow">${E(group.topic||'Builder group')}</span><h1>${E(group.name)}</h1><p>${E(group.description)}</p><div class="member-line">${count(group.memberCount,'member')} · Open group</div></div>${group.joined?`<span class="joined-label">✓ You’re a member</span>${!group.isOwner?`<button class="text-button" data-action="leave-group" data-id="${E(group.id)}">Leave group</button>`:''}`:`<button class="primary" data-action="join-group" data-id="${E(group.id)}">Join group</button>`}</section><div class="feed-layout"><div><div class="section-heading"><h2>Group discussion</h2><span class="hint">${group.joined?'Member discussions stay in the group':'Public updates'}</span></div>${group.joined?composer({groupId:group.id}):`<div class="join-prompt"><strong>Build with this group</strong><p>Join to take part in member discussions and create a project.</p><button class="quiet" data-action="join-group" data-id="${E(group.id)}">Join the conversation</button></div>`}${posts.length?posts.map(p=>postCard(p)).join(''):empty('Start a conversation',group.joined?'Share a question or propose a first experiment.':'There are no public updates yet.','','')}</div><aside><div class="aside-card"><div class="section-heading"><h3>Group projects</h3>${group.joined?`<button class="text-button" data-action="new-project" data-group="${E(group.id)}">＋ New</button>`:''}</div>${projects.length?projects.map(p=>`<a class="aside-idea" href="/projects/${E(p.id)}"><span>▧</span><div><strong>${E(p.title)}</strong><small>${E(p.stage||'forming')}</small></div></a>`).join(''):'<p>No projects yet. Pick an idea and take the first step.</p>'}</div>${group.joined?`<div class="aside-card"><h3>Builders in this group</h3>${members.map(m=>`<div class="member-row">${avatar(m.name)}<span>${E(m.name)}</span></div>`).join('')}</div>`:''}</aside></div>`;}
function renderProjects(){document.title='Projects · Load and Run';$('#page').innerHTML=intro('FROM POSSIBILITY TO PROTOTYPE','See what’s taking shape','Find a project, bring a skill, and help move an idea forward.',`<button class="primary" data-action="new-project">＋ Start a project</button>`)+`<div class="project-grid">${community.projects.map(projectCard).join('')}</div>${community.projects.length?'':empty('Every project starts somewhere','Choose an idea and a small goal. You can find collaborators as you go.','Explore ideas','ideas')}`;}
function renderProject({project,posts,members}){document.title=project.title+' · Load and Run';const source=idea(project.ideaAddress),group=community.groups.find(g=>g.id===project.groupId);$('#page').innerHTML=`<a class="back-link" href="/projects">← All projects</a><div class="project-hero"><div><span class="eyebrow">${group?E(group.name):'Independent project'} · ${E(project.stage||'forming')}</span><h1>${E(project.title)}</h1><p>${E(project.goal)}</p>${source?`<a class="idea-reference" href="${ideaPath(source)}">◇ Building on ${E(source.name)}</a>`:'<span class="idea-reference own-idea">◆ An original idea from the builders</span>'}</div>${project.joined?'<span class="joined-label">✓ You’re on the project</span>':group&&!group.joined?`<a class="button primary" href="/groups/${E(group.id)}">Join the group first →</a>`:`<button class="primary" data-action="join-project" data-id="${E(project.id)}">Join the project</button>`}</div><div class="feed-layout"><div><div class="section-heading"><h2>Project updates</h2>${project.canManage?`<button class="quiet" data-action="project-settings" data-id="${E(project.id)}">Edit project</button>`:''}</div>${project.joined?composer({projectId:project.id}):''}${posts.length?posts.map(p=>postCard(p)).join(''):empty('A place for the work in progress','Share progress, decisions, experiments, and what you need next.','','')}</div><aside><div class="aside-card repo-card"><span class="eyebrow">THE CODE LIVES ON GITHUB</span><h3>Repository</h3>${project.repository?`<a class="repo-name" href="${E(project.repository.url)}" target="_blank" rel="noopener noreferrer">${E(project.repository.fullName)} ↗</a><p>${E(project.repository.description||'Project source code on GitHub.')}</p><p class="hint">${E(project.repository.language||'Source code')} · ${E(project.repository.license?.name||'No license detected')}</p><p class="hint">Linked repository · checked ${date(project.repository.fetchedAt)}</p><div class="repo-links"><a href="${E(project.repository.url)}/issues" target="_blank" rel="noopener noreferrer">Issues ↗</a><a href="${E(project.repository.url)}/pulls" target="_blank" rel="noopener noreferrer">Pull requests ↗</a></div>`:'<p>Link a public repository so builders can explore the code and contribute through GitHub.</p>'}${project.canManage?`<button class="quiet wide" data-action="repository" data-id="${E(project.id)}">${project.repository?'Change repository':'Link GitHub repository'}</button>`:''}<p class="hint">Joining here does not grant GitHub access. Check the repository’s own contribution and license terms.</p></div><div class="aside-card"><h3>Where you can help</h3><p>${E(project.helpNeeded||'Join the project discussion to find a first contribution.')}</p><span class="hint">${count(project.memberCount,'builder')}</span>${project.joined?members.map(m=>`<div class="member-row">${avatar(m.name)}<span>${E(m.name)}</span></div>`).join(''):''}</div></aside></div>`;}
function renderPost({post,comments}){document.title='Discussion · Load and Run';$('#page').innerHTML=`<div class="discussion-page"><a class="back-link" href="/feed">← Feed</a>${postCard(post,true)}<section class="comments"><h2>Discussion</h2>${comments.length?comments.map(comment=>`<article class="comment">${avatar(comment.author?.name)}<div><strong>${E(comment.author?.name)}</strong><small>${date(comment.created)}</small><p>${E(comment.content)}</p></div></article>`).join(''):'<p class="hint">No comments yet. Bring a question or a useful next step.</p>'}<form id="comment-form"><label for="comment-content">Add to the conversation</label><textarea id="comment-content" name="content" maxlength="3000" rows="3" required placeholder="A question, a suggestion, or something you can help with…"></textarea><button class="primary">${session.user?'Post comment':'Sign in to comment'}</button><p class="error" id="comment-error" role="alert" hidden></p></form></section></div>`;$('#comment-form').onsubmit=event=>{event.preventDefault();const content=$('#comment-content').value;requireAccount(async()=>{try{await api(`community/posts/${post.id}/comments`,{content});await refresh();}catch(error){const el=$('#comment-error');if(el){el.hidden=false;el.textContent=error.message;}else toast(error.message);}});};}
function renderAbout(){$('#page').innerHTML=intro('LOAD AND RUN','A community for taking the next step','Find an idea worth exploring and people who want to build it with you.')+`<div class="about-grid">${[['Discover','Read the idea repository, inspect original sources, and explore licensed reference code. Discovery and public updates are open to visitors.'],['Join','Create a builder account to save ideas, comment, share updates, and join groups or projects.'],['Build together','Groups bring people together around a shared interest. Projects turn that interest into a goal, a team, and a GitHub repository.'],['Keep the evidence close','Explore unrealized visions, research prototypes, and unfinished directions. Each brief explains the original ambition, what was built, and a testable next step, with sources and software reuse terms.']].map(([title,copy])=>`<section class="aside-card"><h2>${title}</h2><p>${copy}</p></section>`).join('')}</div>`;}

function submitForm(title,fields,onSubmit,button='Save') {modal(title,`<form id="action-form">${fields}<button class="primary wide">${E(button)}</button></form>`);$('#action-form').onsubmit=async event=>{event.preventDefault();const submit=event.target.querySelector('button[type=submit],button.primary');submit.disabled=true;try{await onSubmit(Object.fromEntries(new FormData(event.target)));}catch(error){formError(error);submit.disabled=false;}};}
function newGroup(){return requireAccount(()=>submitForm('Start a builder group','<p class="form-intro">Give people a shared question to gather around. The group page is public; member discussions stay inside unless you publish an update.</p><label for="group-name">Group name</label><input id="group-name" name="name" maxlength="100" required placeholder="A name people can rally around"><label for="group-description">What brings you together?</label><textarea id="group-description" name="description" maxlength="2000" rows="4" required></textarea><label for="group-topic">Topic</label><input id="group-topic" name="topic" maxlength="80" placeholder="Local-first tools, learning, creative coding…">',async fields=>{const group=await api('community/groups',fields);close();community=await api('community');await go('/groups/'+group.id);},'Create group'));}
function newProject(preset={}) {return requireAccount(()=>submitForm('Start a project',`<p class="form-intro">Choose a small, concrete goal. Build your own idea, or start from one in the repository. You can link a GitHub repository after creating the project.</p><label for="project-title">Project name</label><input id="project-title" name="title" maxlength="150" required><label for="project-goal">What will the first version do?</label><textarea id="project-goal" name="goal" rows="3" maxlength="3000" required>${E(idea(preset.ideaAddress)?.details?.buildPlan.firstMilestone||'')}</textarea><label for="project-idea">Starting point</label><select id="project-idea" name="ideaAddress"><option value="" ${preset.ideaAddress?'':'selected'}>My own idea — start from scratch</option>${catalog.map(i=>`<option value="${E(i.addr)}" ${preset.ideaAddress===i.addr?'selected':''}>${E(i.name)}</option>`).join('')}</select><label for="project-group">Group</label><select id="project-group" name="groupId"><option value="">Independent project</option>${community.groups.filter(g=>g.joined).map(g=>`<option value="${E(g.id)}" ${preset.groupId===g.id?'selected':''}>${E(g.name)}</option>`).join('')}</select><label for="project-help">What help would you welcome?</label><input id="project-help" name="helpNeeded" maxlength="1000" placeholder="Design, prototyping, testing, research…">`,async fields=>{const project=await api('community/projects',{...fields,ideaAddress:fields.ideaAddress||undefined,groupId:fields.groupId||undefined});close();community=await api('community');await go('/projects/'+project.id);},'Create project'));}
function compose(scope={},draft=''){const project=community.projects.find(p=>p.id===scope.projectId);const relatedIdeas=project?.ideaAddress?catalog.filter(i=>i.addr===project.ideaAddress):catalog;return requireAccount(()=>submitForm('Share with the community',`<label for="post-content">What are you working on?</label><textarea id="post-content" name="content" maxlength="4000" rows="6" required placeholder="Share progress, ask for help, or start a useful conversation…">${E(draft)}</textarea><div class="form-columns"><div><label for="post-kind">Post type</label><select id="post-kind" name="kind"><option value="update">Update or discussion</option><option value="help">Looking for help</option></select></div><div><label for="post-visibility">Who can read it?</label><select id="post-visibility" name="visibility">${scope.groupId||scope.projectId?'<option value="members">Group / project members</option>':''}<option value="public">Everyone</option></select></div></div><label for="post-idea">Related idea (optional)</label><select id="post-idea" name="ideaAddress"><option value="">No idea attached</option>${relatedIdeas.map(i=>`<option value="${E(i.addr)}">${E(i.name)}</option>`).join('')}</select>`,async fields=>{await api('community/posts',{...fields,...scope,ideaAddress:fields.ideaAddress||undefined});close();await refresh();toast('Your update is posted.');},'Post update'));}
function propose(){return requireAccount(()=>submitForm('Propose an idea','<p class="form-intro">Describe the specific opportunity, name related work, and include source and license evidence. Submissions are reviewed before entering the repository.</p><label for="proposal-title">Idea title</label><input id="proposal-title" name="title" maxlength="150" required><label for="proposal-summary">What should builders explore?</label><textarea id="proposal-summary" name="summary" rows="5" maxlength="4000" required></textarea><label for="proposal-source">Source material URL</label><input id="proposal-source" name="sourceUrl" type="url" required placeholder="https://…"><label for="proposal-license">Source code license URL</label><input id="proposal-license" name="licenseUrl" type="url" required placeholder="https://…">',async fields=>{await api('community/ideas',fields);close();toast('Idea submitted for review. It is not public yet.');},'Submit for review'));}
function repository(project){return requireAccount(()=>submitForm('Link a GitHub repository',`<p class="form-intro">Link a public repository for this project. This adds a code link and metadata; GitHub controls repository access.</p><label for="repository-url">Public repository URL</label><input id="repository-url" name="url" type="url" required placeholder="https://github.com/owner/repository" value="${E(project.repository?.url||'')}">`,async fields=>{await api('community/projects/'+project.id+'/repository',fields);close();await refresh();toast('GitHub repository linked.');},'Link repository'));}
function projectSettings(project){submitForm('Project direction',`<label for="project-stage">Stage</label><select id="project-stage" name="stage">${['forming','building','testing','shipped'].map(s=>`<option ${project.stage===s?'selected':''}>${s}</option>`).join('')}</select><label for="project-goal">Goal</label><textarea id="project-goal" name="goal" maxlength="3000" rows="4" required>${E(project.goal)}</textarea><label for="project-help">Help needed</label><input id="project-help" name="helpNeeded" maxlength="1000" value="${E(project.helpNeeded||'')}">`,async fields=>{await api('community/projects/'+project.id+'/settings',fields);close();await refresh();},'Save project');}
document.addEventListener('click',async event=>{
  const anchor=event.target.closest('a');if(anchor?.dataset.ideaSection){event.preventDefault();document.getElementById(anchor.dataset.ideaSection)?.scrollIntoView({block:'start'});history.replaceState({},'',location.pathname+'#'+anchor.dataset.ideaSection);return;}if(anchor?.getAttribute('href')?.startsWith('/')&&!event.metaKey&&!event.ctrlKey&&!event.shiftKey){event.preventDefault();if($('#modal').open)close();return go(anchor.getAttribute('href'));}
  const button=event.target.closest('button');if(!button)return;
  if(button.dataset.license){const item=idea(button.dataset.license);if(item)modal('License & reuse',licensePanel(item));return;}
  const action=button.dataset.action,id=button.dataset.id;
  try{
    if(action==='theme'){const next=document.body.dataset.theme==='paper'?'phosphor':'paper';try{localStorage.setItem('lr-theme-mac',JSON.stringify(next));}catch{}document.body.dataset.theme=next;applyTheme();return;}if(action==='close')return close();if(action==='login'||action==='register')return auth(action);
    if(action==='setup-account')return go('/account/setup');
    if(action==='account' && session.demo)return modal('Offline demo identity','<p>You are using a fictional builder. Community edits stay in this process and reset when the demo restarts. Full sign-in, Spaces and AI require your own Worker setup.</p>');
    if(action==='account')return modal('Your builder account',`<div class="account-card">${avatar(session.user.name)}<h2>${E(session.user.name)}</h2><p>Keep your spaces, widgets, and saved ideas together.</p>${session.authProvider==='workos'?'<p class="hint">Use your email or social account to sign in.</p>':''}${session.features?.spaces?'<a class="button quiet wide" href="/spaces">Your spaces</a>':''}<a class="button quiet wide" href="/saved">Saved ideas</a><button class="text-button" data-action="logout">Sign out</button></div>`);
    if(action==='logout'){const result=await api('logout',{});session={};close();const logoutURL=workosLogoutURL(result.logoutUrl);if(logoutURL){location.assign(logoutURL);return;}await refresh();return;}
    if(action==='ideas'||action==='groups')return go('/'+action);if(action==='reset-ideas'){query='';topic='All';ideaHistory='All';return go('/ideas');}
    if(action==='new-group')return newGroup();if(action==='new-project')return newProject({groupId:button.dataset.group,ideaAddress:button.dataset.idea});
    if(action==='compose')return compose({groupId:button.dataset.group,projectId:button.dataset.project});if(action==='propose')return propose();
    if(action==='feed-mode'){if(button.dataset.mode==='joined'&&!session.user)return auth('register',()=>{feedMode='joined';renderFeed();});feedMode=button.dataset.mode;return renderFeed();}
    if(action==='save')return requireAccount(async()=>{const result=await api('community/bookmarks',{ideaAddress:id});saved=await api('community/bookmarks');await renderRoute();toast(result.saved?'Idea saved.':'Idea removed from saved.');});
    if(action==='idea-to-space')return spacesApp.addIdea(id);
    if(action==='join-group'||action==='join-project')return requireAccount(async()=>{await api('community/'+(action==='join-group'?'groups':'projects')+'/'+id+'/join',{});await refresh();toast('You’re in. Welcome to the team.');});
    if(action==='leave-group'){await api('community/groups/'+id+'/leave',{});await refresh();return;}
    if(action==='react')return requireAccount(async()=>{const result=await api('community/posts/'+id+'/react',{});const post=community.posts.find(p=>p.id===id);if(post)Object.assign(post,{reacted:result.reacted,reactionCount:result.reactionCount});button.textContent=`${result.reacted?'♥':'♡'} ${result.reactionCount}`;button.setAttribute('aria-pressed',String(result.reacted));if(!button.isConnected)await renderRoute();});
    if(action==='remove-post'){await api('community/posts/'+id+'/remove',{});await refresh();return;}
    if(action==='repository'){const project=community.projects.find(p=>p.id===id);if(project)return repository(project);}
    if(action==='project-settings'){const project=community.projects.find(p=>p.id===id);if(project)return projectSettings(project);}
    if(action==='report')return requireAccount(()=>submitForm('Report a post','<label for="report-reason">What should the moderators know?</label><textarea id="report-reason" name="reason" maxlength="2000" rows="4" required></textarea>',async fields=>{await api('community/reports',{postId:id,...fields});close();toast('Report sent to the moderation queue.');},'Submit report'));
  }catch(error){toast(error.message);}
});
window.addEventListener('popstate',()=>refresh().catch(error=>toast(error.message)));
document.addEventListener('keydown',event=>{if(event.key==='/'&&!event.ctrlKey&&!event.metaKey&&!event.target.closest('input,textarea,select,[contenteditable]')&&!$('#modal').open){event.preventDefault();go('/ideas').then(()=>$('#idea-search')?.focus());}});

try {
  const [source,activeSession] = await Promise.all([fetch('/data.json').then(r=>{if(!r.ok)throw Error('Idea repository unavailable.');return r.json();}),api('session')]);
  catalog=source.blueprints.filter(item=>isFreeToUseEntry(item)&&hasDetailedBrief(item));session=activeSession;await refresh();
}catch(error){$('#community-root').innerHTML=`<main class="startup-error"><h1>We couldn’t connect</h1><p>${E(error.message)}</p><button onclick="location.reload()">Reload</button></main>`;}
