import {sources,moduleData as module} from './practice-module.js';
export function createPracticeApp({toast = () => {}} = {}) {
let root = null, controller = null;
const $=s=>root?.querySelector(s), E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='lr-practice-v1';
const freshState=()=>({step:0,attempt:'',revision:'',transfer:'',reflection:'',checks:[],complete:false});
let state=freshState(), storageOK=true;
function restore(){try{const saved=JSON.parse(localStorage.getItem(key)), next=freshState();if(saved&&typeof saved==='object'){for(const k of ['attempt','revision','transfer','reflection'])next[k]=typeof saved[k]==='string'?saved[k]:'';next.step=Number.isInteger(saved.step)?Math.max(0,Math.min(4,saved.step)):0;next.checks=Array.isArray(saved.checks)?saved.checks.filter(x=>Number.isInteger(x)&&x>=0&&x<4):[];next.complete=saved.complete===true;}state=next;storageOK=true;}catch{storageOK=false;}}
function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{storageOK=false;}const el=$('#save-status');if(el)el.textContent=storageOK?'Saved on this device':'Saving unavailable. Keep this tab open or download your notes.';}
const action=(href,label,primary=false)=>`<a class="button ${primary?'primary':''}" href="${href}">${label}</a>`;
const caps=[['01','Notice hidden assumptions','Separate what you see from the story you tell.','Full session · About 15 min'],['02','See the system','Trace relationships, feedback, and consequences.','Practice preview'],['03','Combine perspectives','Borrow a useful lens from another field.','Practice preview'],['04','Choose worthwhile questions','Find what matters, and who it matters to.','Practice preview'],['05','Imagine & test alternatives','Make a possibility concrete enough to challenge.','Practice preview'],['06','Learn together','Improve the tools and practices of a group.','Practice preview']];
function top(active){return `<div class="section-top"><span class="mono">THE PRACTICE ROOM / 001</span><span class="mono">HUMAN + AGENT</span></div><nav class="tabs" aria-label="Practice navigation">${[['hub','Capabilities'],['resources','Resources'],['agent','Agent package']].map(([id,label])=>`<a href="#${id}" ${active===id?'aria-current="page"':''}>${label}</a>`).join('')}</nav>`;}
function hub(){return top('hub')+`<section class="hero"><div><span class="eyebrow">LEARN TO SEE. LEARN TO QUESTION. LEARN TO MAKE.</span><h1>Good ideas begin<br>with better thinking.</h1><p>Develop judgment, imagination, and the ability to change things with others. Start with an everyday question. No project needed.</p><div class="actions">${action('#session',state.complete?'Revisit your practice ↗':state.attempt?'Continue practicing ↗':'Try a first practice ↗',true)}${action('#resources','Explore resources')}</div><small>One situation. A new perspective. A better next attempt.</small></div><div class="thinking-map" aria-label="Practice cycle: notice, question, reframe, test, reflect"><div class="map-top mono">THINKING IS A PRACTICE</div><div class="map-row"><span>01<br><b>Notice</b></span><i>→</i><span>02<br><b>Question</b></span></div><div class="map-center">↙ &nbsp; A DIFFERENT POSSIBILITY &nbsp; ↗</div><div class="map-row"><span>04<br><b>Test</b></span><i>←</i><span>03<br><b>Reframe</b></span></div><div class="map-bottom mono">↳ REFLECT. REVISE. TRY AGAIN.</div></div></section><section class="featured"><div><span class="eyebrow">${state.attempt?'YOUR PRACTICE, IN PROGRESS':'START HERE · A SMALL SITUATION, A BIGGER LENS'}</span><h2>Notice hidden assumptions</h2><p>A messy shared kitchen. A proposed leaderboard.<br>What are we taking for granted?</p><div class="pills"><span>15 MINUTES</span><span>NO PREPARATION</span><span>${state.complete?'SELF-REVIEW SAVED':state.attempt?'DRAFT SAVED':'GUIDED SESSION'}</span></div></div>${action('#session',state.attempt?'Open your session →':'Enter the practice →',true)}</section><div class="section-heading"><h2>Capabilities to carry anywhere</h2><span class="muted">A repertoire, not a syllabus.</span></div><div class="cap-grid">${caps.map(([id,title,copy,note],i)=>`<a class="cap" href="${i?'#preview-'+i:'#session'}"><span class="cap-num">${id} /</span><h3>${title} <span>↗</span></h3><p>${copy}</p><small>${note}</small></a>`).join('')}</div><section class="bottom-callout"><div><h2>The same practice, shared with an agent.</h2><p>Methods, sources, challenges, and review criteria in one portable package.</p></div>${action('#agent','Use with an agent →')}</section>`;}
function resources(){return top('resources')+`<div class="page-intro"><span class="eyebrow">READ WITH A QUESTION IN MIND</span><h1>Three lenses.<br>More room to think.</h1><p>Complementary influences, with different aims and assumptions. Use them to challenge your thinking—not as a single doctrine.</p></div><div class="resources">${sources.map(s=>`<article class="resource"><div><span class="eyebrow">${s.lens}</span><h2>${s.author}</h2><p class="source-title">${s.title}</p><small>${s.year}</small></div><div><p>${s.summary}</p><h3>Bring it into practice</h3><p>${s.practice}</p><details><summary>A critical question to keep open</summary><p>${s.critique}</p></details><div class="source-links"><a href="${s.url}" target="_blank" rel="noreferrer">Read the original ↗</a>${s.related.map(([title,url])=>`<a href="${url}" target="_blank" rel="noreferrer">${title} ↗</a>`).join('')}</div></div></article>`).join('')}</div><section class="bottom-callout"><p>Reading is a resource. A changed explanation is evidence of practice.</p>${action('#session','Put a lens to work →',true)}</section>`;}
function agent(){return top('agent')+`<div class="page-intro"><span class="eyebrow">ONE MODULE · TWO WAYS TO PRACTICE</span><h1>A field guide<br>your agent can use.</h1><p>Give an agent the same methods and challenges you use. Invite it to surface assumptions, test alternatives, and make its reasoning open to review.</p></div><div class="agent-grid"><section class="panel"><span class="eyebrow">PACKAGE 001 / VERSION 1</span><h2>Notice hidden assumptions</h2><p>A portable JSON module with original practice material and links to the sources.</p><ul><li>5 thinking methods</li><li>Initial attempt, revision, and transfer tasks</li><li>4 evidence-based review criteria</li><li>3 source perspectives and their limitations</li></ul><button class="primary" data-download="module">Download module .json ↓</button><details><summary>Inspect the complete package</summary><pre>${E(JSON.stringify(module,null,2))}</pre></details></section><section class="panel agent-instructions"><span class="eyebrow">HOW TO USE IT</span><ol><li>Download and attach the module in your agent conversation.</li><li>Ask it to guide a session or apply the methods to a question.</li><li>Compare its reasoning with the criteria. Challenge unsupported conclusions.</li></ol><h3>A starting prompt</h3><blockquote>Use this module to guide me through a practice. Ask for my first attempt before giving hints. Keep my initial and revised reasoning visible, and help me review evidence of change.</blockquote><button data-copy>Copy starting prompt</button><p class="muted">This is runtime guidance, not permanent model training. No agent is connected or being evaluated in this preview.</p></section></div>`;}
const names=['First attempt','Another lens','Revision','Transfer','Self-review'];
function field(id,label,placeholder){return `<label for="${id}">${label}</label><textarea id="${id}" data-field="${id}" rows="6" placeholder="${placeholder}">${E(state[id])}</textarea>`;}
function session(){let s=state.step;let content=[`<span class="eyebrow">01 / BEGIN WITH YOUR OWN THINKING</span><h1>What’s really<br>going on here?</h1><div class="scenario"><span class="mono">THE SHARED KITCHEN</span><p>${module.scenario}</p></div>${field('attempt','What might be happening?','Name an assumption behind the leaderboard and suggest a first response.')}<details><summary>Need a small hint?</summary><p>What must be true for a leaderboard to help? Which parts of the situation are observations, and which are explanations?</p></details>`,
`<span class="eyebrow">02 / TRY A DIFFERENT LENS</span><h1>Change the conditions.<br>Change the question.</h1><div class="scenario"><span class="mono">AN ENVIRONMENTAL PERSPECTIVE · AFTER FRESCO</span><p>Instead of assuming people do not care, consider whether cleaning supplies are hard to find, the sink is inaccessible, or responsibilities are unclear.</p></div><p>These are possibilities to investigate, not facts about this kitchen. A leaderboard may motivate some people while making invisible work even less visible.</p><div class="lens-grid"><div><h3>Engelbart’s lens</h3><p>Could the group improve a tool and a shared practice together?</p></div><div><h3>Hamming’s lens</h3><p>Is rewarding cleaners the important question—or understanding why the kitchen becomes unusable?</p></div></div><details><summary>Sources and limits of this perspective</summary><p>This exercise is our synthesis, not a quotation or an endorsed method. Fresco’s social proposals are not proof; Engelbart and Hamming ask different questions.</p>${sources.map(x=>`<a class="source-link" href="${x.url}" target="_blank" rel="noreferrer">${x.author}: ${x.title} ↗</a>`).join('')}</details>`,
`<span class="eyebrow">03 / MAKE YOUR THINKING VISIBLE</span><h1>What would you<br>change now?</h1><details open><summary>Your first attempt</summary><p class="answer">${E(state.attempt)}</p></details>${field('revision','Revisit your response','What changed? Offer another explanation, a small test, and evidence that would change your mind. Who benefits or carries the burden?')}<details><summary>Optional guide for a test</summary><p>Try “If the issue is ___, changing ___ should produce ___. I would reconsider if ___.” Ask someone whose needs your first response might miss.</p></details>`,
`<span class="eyebrow">04 / TAKE THE METHOD SOMEWHERE NEW</span><h1>New situation.<br>Same curious mind.</h1><div class="scenario"><span class="mono">THE NEIGHBORHOOD LIBRARY</span><p>${module.transfer}</p></div>${field('transfer','How would you investigate this decision?','Name a hidden assumption, an overlooked perspective, and a reversible test.')}<details><summary>Optional hint</summary><p>Do bookings describe everyone who uses the library? What would you need to learn from people who never book a room?</p></details>`,
`<span class="eyebrow">05 / LOOK FOR EVIDENCE, NOT A SCORE</span><h1>See how your<br>thinking moved.</h1><p>This is your self-review. No AI has graded your answers. Compare specific passages, including what still needs work.</p><div class="comparison"><article><span class="eyebrow">YOUR FIRST ATTEMPT</span><p class="answer">${E(state.attempt)}</p></article><article><span class="eyebrow">YOUR REVISION</span><p class="answer">${E(state.revision)}</p></article></div><details><summary>Review your library transfer</summary><p class="answer">${E(state.transfer)}</p></details><fieldset><legend>Which evidence can you point to in your answers?</legend>${module.criteria.map((c,i)=>`<label class="check"><input type="checkbox" data-check="${i}" ${state.checks.includes(i)?'checked':''}>${c}</label>`).join('')}</fieldset>${field('reflection','Name one concrete change—and one thing to try next','Compare a phrase from your first attempt with your revision. What remains uncertain? Who could help you test it?')}${state.complete?'<div class="success" role="status">Self-review saved. A next experiment is more useful than a perfect answer.</div>':''}`][s];
return `<div class="session-top"><a href="#hub">← Practice room</a><span id="save-status" class="muted">${storageOK?'Saved on this device':'Saving unavailable. Download notes before leaving.'}</span></div><div class="session-layout"><nav class="step-nav" aria-label="Session steps">${names.map((n,i)=>`<button data-step="${i}" ${i===s?'aria-current="step"':''}><span>0${i+1}</span>${n}</button>`).join('')}<p>About 15 minutes.<br>Take your time.<br>You can come back.</p><button data-download="notes">Download your notes ↓</button></nav><section class="session-paper">${content}<p id="validation" role="alert"></p><div class="session-actions">${s?'<button data-back>← Back</button>':'<span class="muted">A rough first thought is enough.</span>'}<button class="primary" data-next>${s===4?'Save self-review ✓':s===0?'Keep my attempt →':s===1?'Revise my response →':s===2?'Try a new situation →':'Compare my thinking →'}</button></div>${s===4&&state.complete?'<div class="actions"><a href="#resources">Explore another lens ↗</a><a href="/ideas">Apply this to an idea ↗</a><a href="#hub">Back to capabilities →</a></div>':''}</section></div>`;}
const previews=[null,['Map one ordinary system','Choose a recurring delay in your day. Map the people, resources, rules, and feedback that keep it happening.','Draw three connections. Which intervention might move the problem somewhere else?','A useful map includes a feedback loop, a boundary, and a person affected outside that boundary.'],['Borrow a lens','Choose a familiar service. Describe it first as an engineer, then as a caregiver, then as an ecologist.','Where do the explanations disagree? Propose one way to learn which differences matter.','Look for a new relationship, not just new vocabulary. State where the borrowed analogy breaks.'],['Choose a question worth your attention','Write a question you keep returning to. Name who would benefit if you answered it.','What makes it important? What fundamentals would you need? Who might frame it differently?','Separate personal curiosity, social value, and feasibility. None alone settles the choice.'],['Make an alternative testable','Pick an arrangement that feels inevitable. Imagine two different ways it could work.','Design the smallest reversible experiment that distinguishes between the possibilities.','Specify a result that would surprise you, a cost to others, and a stopping condition.'],['Improve how you improve','Recall a group discussion that got stuck. Inspect the tools and practices used together.','Change one tool and one practice. Ask the group what improved and what became harder.','Look for shared understanding and participation, not only speed.']];
function preview(i){const p=previews[i];return top('hub')+`<div class="page-intro"><a href="#hub">← All capabilities</a><p class="eyebrow">CAPABILITY ${caps[i][0]} / SELF-GUIDED PREVIEW</p><h1>${caps[i][1]}</h1><p>${caps[i][2]}</p></div><section class="panel preview-panel"><h2>${p[0]}</h2><p>${p[1]}</p><h3>Try it</h3><p>${p[2]}</p><h3>Review your thinking</h3><p>${p[3]}</p><p class="muted">This is a short exercise to try on paper or with a partner. The complete interactive session is available for noticing assumptions.</p>${action('#session','Try the guided session →',true)}</section>`;}
function render(){if (!root) return; const route=location.hash.slice(1)||'hub';root.innerHTML=route==='session'?session():route==='resources'?resources():route==='agent'?agent():/^preview-[1-5]$/.test(route)?preview(Number(route.at(-1))):hub();document.title=(route==='session'?module.title:'Practice')+' · Load and Run';}
function changeStep(i){state.step=i;save();render();document.querySelector('#main')?.focus();window.scrollTo(0,0);}
function mount(element) {
  dispose();
  restore();
  root = element;
  root.classList.add('practice-page');
  controller = new AbortController();
  const {signal} = controller;
root.addEventListener('input',e=>{if(e.target.dataset.field){state[e.target.dataset.field]=e.target.value;state.complete=false;save();}}, {signal});
root.addEventListener('change',e=>{if(e.target.dataset.check!==undefined){const i=Number(e.target.dataset.check);state.checks=e.target.checked?[...new Set([...state.checks,i])]:state.checks.filter(x=>x!==i);save();}}, {signal});
root.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-next')){const f=['attempt',null,'revision','transfer','reflection'][state.step];if(f&&!state[f].trim()){$('#validation').textContent='Add a few words to keep this part of your thinking. Your other answers are still here.';$('#'+f).focus();return;}if(state.step===4){state.complete=true;save();render();}else changeStep(state.step+1);}if(b.hasAttribute('data-back'))changeStep(state.step-1);if(b.dataset.step!==undefined)changeStep(Number(b.dataset.step));if(b.dataset.download){const data=b.dataset.download==='module'?module:{module_id:module.id,...state};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=b.dataset.download==='module'?'notice-hidden-assumptions.json':'my-practice-notes.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}if(b.hasAttribute('data-copy')){try{await navigator.clipboard.writeText($('blockquote').textContent);b.textContent='Copied ✓';}catch{toast('Copy unavailable. Select and copy the prompt above.');}}}, {signal});
window.addEventListener('hashchange',()=>{if (!isPracticePath(location.pathname)) return;render();document.querySelector('#main')?.focus();window.scrollTo(0,0);}, {signal});
  render();
}
function dispose() {controller?.abort();controller = null;root?.classList.remove('practice-page');root = null;}
return {mount, dispose};
}

export function isPracticePath(path) {return ['/practice', '/practice/', '/practice.html'].includes(path);}
