export const sources = [
{id:'engelbart',author:'Douglas Engelbart',title:'Augmenting Human Intellect',year:'1962 · Framework',lens:'Collective capability',summary:'Tools, language, skills, and working methods form a system. Improving how we improve can expand what a group is able to understand and do.',practice:'Look beyond a better tool: change a practice and a tool together, then observe the result.',critique:'A powerful account of augmentation; it does not settle who chooses the goals, who gets access, or how power is shared.',url:'https://www.dougengelbart.org/content/view/138/',related:[['Team and biography','https://www.dougengelbart.org/content/view/183/'],['Original paper archive','https://www.dougengelbart.org/mousesite/EngelbartPapers/Contents.html']]},
{id:'fresco',author:'Jacque Fresco',title:'Designing the Future',year:'Book · Proposals',lens:'Environment & behavior',summary:'Fresco asks how material conditions and social arrangements shape behavior, and imagines alternatives to inherited institutions.',practice:'Before blaming a person, inspect the conditions, incentives, and constraints around their actions.',critique:'These are proposals, not independent evidence that a whole social system would work. Ask about governance, consent, tradeoffs, and testability.',url:'https://files.thevenusproject.com/hotlink-ok/designing_the_future_ebook/Jacque%20Fresco%20-%20Designing%20the%20Future.pdf',related:[['His environmental perspective','https://www.thevenusproject.com/multimedia/changing_human_nature/']]},
{id:'hamming',author:'Richard Hamming',title:'The Art of Doing Science and Engineering',year:'Book · Learning to Learn',lens:'The craft of discovery',summary:'Learning how to think involves studying examples of discovery, developing fundamentals, and deliberately choosing questions worth pursuing.',practice:'Ask what makes this question important and what you would need to learn to make real progress.',critique:'Lessons from a distinguished technical career are situated examples, not a universal recipe. Examine whose successes and questions are missing.',url:'https://press.stripe.com/the-art-of-doing-science-and-engineering',related:[['Read the preface (PDF)','https://savage.nps.edu/hamming/HammingLearningToLearnRecovered/chapters/Hamming01.pdf']]}
];
export const moduleData = {
 schema_version:1,id:'notice-hidden-assumptions',title:'Notice hidden assumptions',audience:['humans','AI agents'],purpose:'Separate observations from explanations, imagine alternatives, and design a small test that considers who benefits.',
 scenario:'The shared kitchen at a community space is often left messy. Someone suggests a public leaderboard of the people who clean the most.',
 transfer:'A library wants to replace its quiet reading area with collaborative tables because group bookings have increased. What should it question before making the change?',
 methods:['Record observations separately from interpretations.','Name one assumption and what would change if it were false.','Generate explanations from at least two perspectives, including someone affected.','Propose a small, reversible test and a result that would change your mind.','Revise your explanation and carry the method to an unfamiliar setting.'],
 tasks:[{id:'attempt',prompt:'What might be happening? Name an assumption behind the leaderboard and suggest a first response.'},{id:'revision',prompt:'Revisit your first response. What changed? Propose an alternative explanation, a small test, and evidence that would change your mind. Who might be helped or burdened?'},{id:'transfer',prompt:'Apply the method to the library. Name a hidden assumption, an overlooked perspective, and a reversible test.'}],
 criteria:['I separated an observation from an explanation.','I considered a plausible alternative and someone affected.','I proposed a test and evidence that could change my mind.','I used the method in the library example, beyond the kitchen.'],
 sources,
 agent_instructions:'Use this as runtime guidance, not permanent model training. Ask for an initial attempt before offering perspectives. Keep hints optional. Preserve the first attempt. Invite revision and then an unfamiliar transfer attempt. Compare concrete passages against the criteria; distinguish observed evidence, missing evidence, and uncertainty. Do not invent scores, claim a person has mastered a capability, or claim a tool run happened. Ask for human self-review and a next experiment. Treat the sources as different perspectives, not a shared doctrine.'
};
